CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "CarKategori" AS ENUM ('LILLE', 'MELLEMKLASSE', 'STATIONCAR', 'EL', 'VAREBIL');
CREATE TYPE "GearType" AS ENUM ('MANUEL', 'AUTOMATIK');
CREATE TYPE "BreendstofType" AS ENUM ('BENZIN', 'DIESEL', 'EL', 'HYBRID');
CREATE TYPE "CarStatus" AS ENUM ('LEDIG', 'RESERVERET', 'UDLEJET', 'SERVICE', 'UDGAAET');
CREATE TYPE "BookingStatus" AS ENUM ('AFVENTER', 'BEKRAEFTET', 'AKTIV', 'UDLEJET', 'AFSLUTTET', 'ANNULLERET');
CREATE TYPE "BetalingStatus" AS ENUM ('AFVENTER', 'BETALT', 'DELVIST', 'REFUNDERET');
CREATE TYPE "ExtraType" AS ENUM ('CHAUFFOR', 'BARNESTOL', 'SELVRISIKO', 'GPS');
CREATE TYPE "SigningProvider" AS ENUM ('MITID', 'PENNEO', 'SCRIVE', 'DROPBOX');
CREATE TYPE "PaymentMethod" AS ENUM ('MOBILEPAY', 'KORT', 'KONTANT');
CREATE TYPE "PaymentStatus" AS ENUM ('AFVENTER', 'BETALT', 'FEJL', 'REFUNDERET');
CREATE TYPE "InspectionType" AS ENUM ('FOER', 'EFTER');
CREATE TABLE "customers" ("id" TEXT NOT NULL,"navn" TEXT NOT NULL,"email" TEXT NOT NULL,"telefon" TEXT NOT NULL,"adresse" TEXT,"postnr" TEXT,"by" TEXT,"koerekort_verificeret" BOOLEAN NOT NULL DEFAULT false,"koerekort_url" TEXT,"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "customers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "cars" ("id" TEXT NOT NULL,"navn" TEXT NOT NULL,"reg_nr" TEXT NOT NULL,"kategori" "CarKategori" NOT NULL,"gear" "GearType" NOT NULL,"braendstof" "BreendstofType" NOT NULL,"saeder" INTEGER NOT NULL DEFAULT 5,"pris_dag" INTEGER NOT NULL,"depositum" INTEGER NOT NULL DEFAULT 3000,"km_per_dag" INTEGER NOT NULL DEFAULT 300,"status" "CarStatus" NOT NULL DEFAULT 'LEDIG',"beskrivelse" TEXT,"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "cars_pkey" PRIMARY KEY ("id"));
CREATE TABLE "car_images" ("id" TEXT NOT NULL,"car_id" TEXT NOT NULL,"url" TEXT NOT NULL,"raekkefoelge" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "car_images_pkey" PRIMARY KEY ("id"));
CREATE TABLE "bookings" ("id" TEXT NOT NULL,"booking_nr" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"car_id" TEXT NOT NULL,"start" TIMESTAMP(3) NOT NULL,"slut" TIMESTAMP(3) NOT NULL,"status" "BookingStatus" NOT NULL DEFAULT 'AFVENTER',"total_pris" INTEGER NOT NULL,"betalingsstatus" "BetalingStatus" NOT NULL DEFAULT 'AFVENTER',"noter" TEXT,"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "bookings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "booking_extras" ("id" TEXT NOT NULL,"booking_id" TEXT NOT NULL,"type" "ExtraType" NOT NULL,"pris" INTEGER NOT NULL,CONSTRAINT "booking_extras_pkey" PRIMARY KEY ("id"));
CREATE TABLE "contracts" ("id" TEXT NOT NULL,"booking_id" TEXT NOT NULL,"pdf_url" TEXT,"signeret_af" TEXT,"udbyder" "SigningProvider" NOT NULL DEFAULT 'PENNEO',"signeret_tid" TIMESTAMP(3),"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "contracts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments" ("id" TEXT NOT NULL,"booking_id" TEXT NOT NULL,"beloeb" INTEGER NOT NULL,"metode" "PaymentMethod" NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'AFVENTER',"transaktion_id" TEXT,"quickpay_id" TEXT,"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "payments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "inspections" ("id" TEXT NOT NULL,"booking_id" TEXT NOT NULL,"type" "InspectionType" NOT NULL,"km" INTEGER,"braendstof" INTEGER,"billeder" TEXT[],"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "inspections_pkey" PRIMARY KEY ("id"));
CREATE TABLE "damages" ("id" TEXT NOT NULL,"booking_id" TEXT NOT NULL,"beskrivelse" TEXT NOT NULL,"billeder" TEXT[],"omkostning" INTEGER NOT NULL DEFAULT 0,"oprettet" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "damages_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "customers_email_key" ON "customers"("email");
CREATE UNIQUE INDEX "cars_reg_nr_key" ON "cars"("reg_nr");
CREATE UNIQUE INDEX "bookings_booking_nr_key" ON "bookings"("booking_nr");
CREATE UNIQUE INDEX "contracts_booking_id_key" ON "contracts"("booking_id");
ALTER TABLE "car_images" ADD CONSTRAINT "car_images_car_id_fkey" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_car_id_fkey" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "booking_extras" ADD CONSTRAINT "booking_extras_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inspections" ADD CONSTRAINT "inspections_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "damages" ADD CONSTRAINT "damages_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
